import { AchievementCategory } from '@/types';

export interface AchievementDefinition {
  key: string;
  name: string;
  name_mn: string;
  description: string;
  description_mn: string;
  icon: string;
  category: AchievementCategory;
  threshold: number;
  activity_type?: string;
}

export const DEFAULT_ACHIEVEMENTS: AchievementDefinition[] = [
  // ==================== DISTANCE (Single Activity) ====================
  {
    key: 'first_5k',
    name: 'First 5K',
    name_mn: 'Эхний 5 км',
    description: 'Complete your first 5K run',
    description_mn: 'Эхний 5 км гүйлтээ гүйцээ',
    icon: '🎯',
    category: 'distance',
    threshold: 5000,
    activity_type: 'Run',
  },
  {
    key: 'first_10k',
    name: 'First 10K',
    name_mn: 'Эхний 10 км',
    description: 'Complete your first 10K run',
    description_mn: 'Эхний 10 км гүйлтээ гүйцээ',
    icon: '🏃',
    category: 'distance',
    threshold: 10000,
    activity_type: 'Run',
  },
  {
    key: 'first_half_marathon',
    name: 'Half Marathon',
    name_mn: 'Хагас марафон',
    description: 'Complete a half marathon (21.1km)',
    description_mn: '21.1 км гүйж хагас марафон гүйцээ',
    icon: '🏅',
    category: 'distance',
    threshold: 21097,
    activity_type: 'Run',
  },
  {
    key: 'first_marathon',
    name: 'Marathon',
    name_mn: 'Марафон',
    description: 'Complete a full marathon (42.2km)',
    description_mn: '42.2 км гүйж бүтэн марафон гүйцээ',
    icon: '🏆',
    category: 'distance',
    threshold: 42195,
    activity_type: 'Run',
  },
  {
    key: 'ultra_50k',
    name: 'Ultra Runner',
    name_mn: 'Ультра гүйгч',
    description: 'Complete an ultra marathon (50km+)',
    description_mn: '50+ км ультра марафон гүйж дуусга',
    icon: '🦸',
    category: 'distance',
    threshold: 50000,
    activity_type: 'Run',
  },

  // ==================== TOTAL DISTANCE ====================
  {
    key: 'total_100k',
    name: '100km Club',
    name_mn: '100 км клуб',
    description: 'Accumulate 100km total distance',
    description_mn: 'Нийт 100 км зай туулсан',
    icon: '💯',
    category: 'total_distance',
    threshold: 100000,
  },
  {
    key: 'total_500k',
    name: '500km Club',
    name_mn: '500 км клуб',
    description: 'Accumulate 500km total distance',
    description_mn: 'Нийт 500 км зай туулсан',
    icon: '🌟',
    category: 'total_distance',
    threshold: 500000,
  },
  {
    key: 'total_1000k',
    name: '1000km Club',
    name_mn: '1000 км клуб',
    description: 'Accumulate 1000km total distance',
    description_mn: 'Нийт 1000 км зай туулсан',
    icon: '👑',
    category: 'total_distance',
    threshold: 1000000,
  },
  {
    key: 'total_2500k',
    name: '2500km Legend',
    name_mn: '2500 км домог',
    description: 'Accumulate 2500km total distance',
    description_mn: 'Нийт 2500 км зай туулсан',
    icon: '🔱',
    category: 'total_distance',
    threshold: 2500000,
  },
  {
    key: 'total_5000k',
    name: '5000km Master',
    name_mn: '5000 км мастер',
    description: 'Accumulate 5000km total distance',
    description_mn: 'Нийт 5000 км зай туулсан',
    icon: '💎',
    category: 'total_distance',
    threshold: 5000000,
  },

  // ==================== STREAKS ====================
  {
    key: 'streak_3',
    name: '3 Day Streak',
    name_mn: '3 хоног дараалан',
    description: 'Work out 3 days in a row',
    description_mn: '3 хоног дараалан дасгал хий',
    icon: '🔥',
    category: 'streak',
    threshold: 3,
  },
  {
    key: 'streak_7',
    name: 'Week Warrior',
    name_mn: '7 хоног дараалан',
    description: 'Work out 7 days in a row',
    description_mn: '7 хоног дараалан дасгал хий',
    icon: '💪',
    category: 'streak',
    threshold: 7,
  },
  {
    key: 'streak_14',
    name: 'Fortnight Fighter',
    name_mn: '14 хоног дараалан',
    description: 'Work out 14 days in a row',
    description_mn: '14 хоног дараалан дасгал хий',
    icon: '⚡',
    category: 'streak',
    threshold: 14,
  },
  {
    key: 'streak_30',
    name: 'Month Master',
    name_mn: '30 хоног дараалан',
    description: 'Work out 30 days in a row',
    description_mn: '30 хоног дараалан дасгал хий',
    icon: '🌙',
    category: 'streak',
    threshold: 30,
  },
  {
    key: 'streak_100',
    name: 'Century Streak',
    name_mn: '100 хоног дараалан',
    description: 'Work out 100 days in a row',
    description_mn: '100 хоног дараалан дасгал хий',
    icon: '🏛️',
    category: 'streak',
    threshold: 100,
  },
  {
    key: 'streak_365',
    name: 'Year of Dedication',
    name_mn: 'Жилийн тууштай байдал',
    description: 'Work out 365 days in a row',
    description_mn: '365 хоног дараалан дасгал хий',
    icon: '🎖️',
    category: 'streak',
    threshold: 365,
  },

  // ==================== ELEVATION ====================
  {
    key: 'elevation_500',
    name: 'Hill Starter',
    name_mn: 'Толгод авирагч',
    description: 'Climb 500m elevation in one activity',
    description_mn: 'Нэг дасгалд 500м өндөрлөг авир',
    icon: '⛰️',
    category: 'elevation',
    threshold: 500,
  },
  {
    key: 'elevation_1000',
    name: 'Mountain Climber',
    name_mn: 'Уул авирагч',
    description: 'Climb 1000m elevation in one activity',
    description_mn: 'Нэг дасгалд 1000м өндөрлөг авир',
    icon: '🏔️',
    category: 'elevation',
    threshold: 1000,
  },
  {
    key: 'elevation_2000',
    name: 'Mountain Goat',
    name_mn: 'Уулын ямаа',
    description: 'Climb 2000m elevation in one activity',
    description_mn: 'Нэг дасгалд 2000м өндөрлөг авир',
    icon: '🐐',
    category: 'elevation',
    threshold: 2000,
  },
  {
    key: 'total_elevation_10k',
    name: 'Everest Base Camp',
    name_mn: 'Эверест суурин',
    description: 'Accumulate 10,000m total elevation',
    description_mn: 'Нийт 10,000м өндөрлөг авир',
    icon: '🗻',
    category: 'elevation',
    threshold: 10000,
  },
  {
    key: 'total_elevation_50k',
    name: 'Everest Summiter',
    name_mn: 'Эверест оргил',
    description: 'Accumulate 50,000m total elevation (5x Everest)',
    description_mn: 'Нийт 50,000м өндөрлөг (5 удаа Эверест)',
    icon: '🚩',
    category: 'elevation',
    threshold: 50000,
  },

  // ==================== MILESTONES ====================
  {
    key: 'first_activity',
    name: 'First Step',
    name_mn: 'Эхний алхам',
    description: 'Complete your first activity',
    description_mn: 'Эхний дасгалаа хий',
    icon: '🚀',
    category: 'milestone',
    threshold: 1,
  },
  {
    key: 'activities_10',
    name: 'Getting Started',
    name_mn: 'Эхлэл',
    description: 'Complete 10 activities',
    description_mn: '10 дасгал хий',
    icon: '🌱',
    category: 'milestone',
    threshold: 10,
  },
  {
    key: 'activities_50',
    name: 'Dedicated',
    name_mn: 'Тууштай',
    description: 'Complete 50 activities',
    description_mn: '50 дасгал хий',
    icon: '🎯',
    category: 'milestone',
    threshold: 50,
  },
  {
    key: 'activities_100',
    name: 'Century',
    name_mn: 'Зуун',
    description: 'Complete 100 activities',
    description_mn: '100 дасгал хий',
    icon: '💯',
    category: 'milestone',
    threshold: 100,
  },
  {
    key: 'activities_500',
    name: 'Veteran',
    name_mn: 'Ахмад',
    description: 'Complete 500 activities',
    description_mn: '500 дасгал хий',
    icon: '🎖️',
    category: 'milestone',
    threshold: 500,
  },
  {
    key: 'activities_1000',
    name: 'Legend',
    name_mn: 'Домог',
    description: 'Complete 1000 activities',
    description_mn: '1000 дасгал хий',
    icon: '👑',
    category: 'milestone',
    threshold: 1000,
  },

  // ==================== SPECIAL ====================
  {
    key: 'early_bird',
    name: 'Early Bird',
    name_mn: 'Эрт босогч',
    description: 'Complete an activity before 6 AM',
    description_mn: 'Өглөөний 6 цагаас өмнө дасгал хий',
    icon: '🌅',
    category: 'special',
    threshold: 6, // before 6am
  },
  {
    key: 'night_owl',
    name: 'Night Owl',
    name_mn: 'Шөнийн шувуу',
    description: 'Complete an activity after 9 PM',
    description_mn: 'Оройн 9 цагаас хойш дасгал хий',
    icon: '🦉',
    category: 'special',
    threshold: 21, // after 9pm
  },
  {
    key: 'weekend_warrior',
    name: 'Weekend Warrior',
    name_mn: 'Амралтын баатар',
    description: 'Complete 4 weekend activities in a month',
    description_mn: 'Сарын турш амралтын өдрүүдэд 4 дасгал хий',
    icon: '⚔️',
    category: 'special',
    threshold: 4,
  },
  {
    key: 'new_year_starter',
    name: 'New Year Starter',
    name_mn: 'Шинэ жилийн эхлэл',
    description: 'Complete an activity on January 1st',
    description_mn: '1-р сарын 1-нд дасгал хий',
    icon: '🎆',
    category: 'special',
    threshold: 1,
  },
  {
    key: 'lunch_runner',
    name: 'Lunch Runner',
    name_mn: 'Үдийн гүйгч',
    description: 'Complete an activity between 12-1 PM',
    description_mn: 'Үдийн 12-13 цагт дасгал хий',
    icon: '🥗',
    category: 'special',
    threshold: 1,
  },

  // ==================== SPEED ====================
  {
    key: 'speed_sub30_5k',
    name: 'Sub-30 5K',
    name_mn: '30 минутаас доош 5К',
    description: 'Complete a 5K run in under 30 minutes',
    description_mn: '5К-г 30 минутаас бага хугацаанд гүй',
    icon: '⚡',
    category: 'speed',
    threshold: 1800, // 30 minutes in seconds
    activity_type: 'Run',
  },
  {
    key: 'speed_sub25_5k',
    name: 'Sub-25 5K',
    name_mn: '25 минутаас доош 5К',
    description: 'Complete a 5K run in under 25 minutes',
    description_mn: '5К-г 25 минутаас бага хугацаанд гүй',
    icon: '🚀',
    category: 'speed',
    threshold: 1500,
    activity_type: 'Run',
  },
  {
    key: 'speed_sub20_5k',
    name: 'Sub-20 5K',
    name_mn: '20 минутаас доош 5К',
    description: 'Complete a 5K run in under 20 minutes',
    description_mn: '5К-г 20 минутаас бага хугацаанд гүй',
    icon: '💨',
    category: 'speed',
    threshold: 1200,
    activity_type: 'Run',
  },
  {
    key: 'speed_sub60_10k',
    name: 'Sub-60 10K',
    name_mn: '60 минутаас доош 10К',
    description: 'Complete a 10K run in under 60 minutes',
    description_mn: '10К-г 60 минутаас бага хугацаанд гүй',
    icon: '🏃‍♂️',
    category: 'speed',
    threshold: 3600,
    activity_type: 'Run',
  },
  {
    key: 'speed_sub50_10k',
    name: 'Sub-50 10K',
    name_mn: '50 минутаас доош 10К',
    description: 'Complete a 10K run in under 50 minutes',
    description_mn: '10К-г 50 минутаас бага хугацаанд гүй',
    icon: '🔥',
    category: 'speed',
    threshold: 3000,
    activity_type: 'Run',
  },
];
